<?php
/**
 * Ho_SimpleBundle
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the H&O Commercial License
 * that is bundled with this package in the file LICENSE_HO.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@h-o.com so we can send you a copy immediately.
 *
 * @category    Ho
 * @package     Ho_SimpleBundle
 * @copyright   Copyright © 2014 H&O (http://www.h-o.nl/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author      Paul Hachmang – H&O <info@h-o.nl>
 */

/** @var $this Ho_SimpleBundle_Block_Bundle_Catalog_Product_View_Type_Option_Fixed */
/** @var $_option Mage_Bundle_Model_Option */
$_option = $this->getOption();

$_selections = $this->getSelections();
?>
<dd<?php if ($_option->getDecoratedIsLast()){?> class="last"<?php }?>>
    <div class="input-box">
        <?php if (count($_selections) == 1 && $_option->getRequired()): ?>
        <input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>"/>
        <?php else:?>
        <ul class="options-list">
            <?php foreach($_selections as $_product): ?>
            <?php /** @var $_product Mage_Catalog_Model_Product */ ?>
            <li>
				<div class="content">
                    <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(100); ?>"
                             width="100" height="100"
                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
                    <h3>
                        <span class="qty"><?php echo $_product->getSelectionQty()*1; ?> x</span>
                        <a class="product-name" href="<?php echo $_product->getProductUrl() ?>"><?php echo $_product->getName(); ?></a>
                    </h3>
                    <?php echo $this->getPriceHtml($_product, true) ?>

                    <?php $_product->getSelectionQty(); ?>
                    <?php if($_option->getRequired()): ?>
                        <?php echo $this->setValidationContainer('bundle-option-'.$_option->getId().'-'.$_product->getSelectionId(), 'bundle-option-'.$_option->getId().'-container') ?>
                    <?php endif; ?>
                </div>
            </li>
            <?php endforeach; ?>
        </ul>
        <div id="bundle-option-<?php echo $_option->getId() ?>-container"></div>
        <?php endif; ?>
    </div>
</dd>
