<?php
/**
 * Ho_SimpleBundle
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the H&O Commercial License
 * that is bundled with this package in the file LICENSE_HO.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@h-o.com so we can send you a copy immediately.
 *
 * @category    Ho
 * @package     Ho_SimpleBundle
 * @copyright   Copyright © 2014 H&O (http://www.h-o.nl/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author      Paul Hachmang – H&O <info@h-o.nl>
 */
?>
<?php
/* @var $this  Ho_SimpleBundle_Block_Catalog_Product_List_Upsell */

$_productCollection = $this->getItemCollection();
$_parentProduct = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>
<?php if ($_productCollection->count()): ?>
<div class="panel panel-default panel-up-sell">
    <div class="panel-heading">
        <h2 class="panel-title"><?php echo Mage::helper('ho_simplebundle')->__('Bundle Discount for %s', $_parentProduct->getName()) ?></h2>
    </div>

    <div class="panel-body products-list">
        <?php foreach ($_productCollection as $_product): ?>
        <div class="item">
            <?php echo Mage::helper('ho_simplebundle')->getProductHtml('simplebundle', $_product, array('limit_characters' => $this->getLimitCharacters())); ?>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
